### ISSUE TITLE
modify to 13*13 board

### ISSUE THREAD

**Issue by da1940430** [tomasmcz/imago#8]
Hi,if I want to modify this program from 19x19 to 13x13, which module do I modify?

(I'm from Taiwan,my English isn’t very good. Sorry!)

**Comment by tomasmcz** [comment]
Hi,

I'm afraid that the board size is hardcoded in many places. I think I was going to take boardsize as a  parameter, but didn't quite get to do that. The fastest approach would probably be to search for `19` in the code and carefully replace that with a variable/parameter for the function concerned.

@SebKuzminsky has a branch called `small-boards`, but it seems he didn't get very far with the actual refactor either (and I don't blame him – the code is a terrible mess).

**Comment by da1940430** [comment]
Thank you for your suggestion, I will try to search for 19 in the code and read  @SebKuzminsky 

 `small-boards`

**Comment by da1940430** [comment]
Hi!

I tried to modify all 19 to 13, but I found a problem, when `griedf_new.find() `called `manual_lines.lines()`  , it will return 19 lines, so the result is no correct.  http://tomasm.cz/imago_doc/  documentation  does not write any about `manual_lines.py` 's infomation, can you tell me? Thank you.

**Comment by SebKuzminsky** [comment]
`manual_lines.py:lines()` currently always returns 19 lines.

The process looks like this:
* `lines()` gets called with the four corners of the board.
* `lines()` calls `_lines()` with the four corners and `n=0`.
* `_lines()`, when called with `n=0`, generates the midline that divides the board area into two equal half-boards, the left side and the right side.  This midline is column 10 of a 19x19 board.  Each half-board consists of an outside edge and the midline.  `_lines()` then calls itself twice: once with the left side and then again with the right side.  Each time it passes itself the corners of the corresponding half-board, and `n=1`.
* `_lines()`, when called with `n=1`, computes the two lines that divide the passed-in board area into three equal parts.  On the left half-board these two lines are columns 4 and 7, which together with columns 1 and 10 (the verticals defined by the passed-in corners) divides the boards into three equal regions (consisting of columns 2 & 3, 5 & 6, and 8 & 9).  `_lines()` then calls itself with each of these thirds, and `n=2`.
* `_lines()`, when called with `n=2`, computes the two lines that divide the passed-in board area into three equal parts, but then just returns these two lines.
* Back in `_lines()` with `n=1` it adds the two vertical lines that it computed (columns 4 & 7), adds the six vertical lines that the three calls to `_lines()` with `n=2` returned (columns 2 & 3, 5 & 6, and 8 & 9), and returns that.
* Back in `_lines()` with `n=0`, it takes the midline it computed (column 10), the 8 lines from the left half-board (2-9), and the 8 lines from the right half-board (11-18), and returns that.
* Finally, back in `lines()` it takes the 17 lines from `_lines()` with `n=0` (2-18) and adds the outside edges defined by the corners originally passed in (columns 1 and 19)/
* `lines()` then runs this algorithm again, but with the corners rotated so that it generates the horizontal lines.

So one way to add support for different sized boards (in `manual_lines.py`) would be like this:
* Add an argument to `lines()` specifying the number of lines to divide the board into (if you pass it 19 you should get the same results as now).  Let's call this new argument `num_lines` for now.
* Add support for new `n` values in `_lines()` that makes it divide the passed-in board area into different numbers of lines.  For a 13x13 you can imagine this:
    * `n=10`: Like `n=0`, but the midline is column 7 (half of a 13x13).  Recurse on each half-board and `n=11` instead of `n=1`.
    * `n=11`: Split the passed-in half-board in half again (on column 4 in the first case), generating "quarter-boards". Recurse on each quarter-board and `n=2`.
    * The `n=2` case is the same as before, find the two lines inside the passed-in corners.
    * Back in the `n=11` case it gets columns 2 & 3 from one quarter-board, adds its midline (column 4), and gets columns 5 & 6 from the other quarter board.
    * Back in the `n=10` case it gets columns 2-6 from one half-board, adds the midline (column 7), and gets columns 8-12 from the other half-board.
    * Back in `lines()` with the new `num_lines=13` it gets columns 2-12 from `_lines()` with `n=10`, adds the outside lines implied by the corners (columns 1 and 13), and it's done.

I think that would work, and it's fairly low effort.  But as we've both experienced, the `lines()`/`_lines()` code is fairly cryptic.  For that reason I'd very much prefer to reorganize all this code to make it more approachable.

I propose replacing the `n` argument with a new `num_lines` argument as mentioned above.  `lines()/_lines()` would have to learn, based on `num_lines` rather than `n`, how to divide the board up into smaller areas and call itself (with the smaller board areas and a modified `num_lines`).

It currently knows the board-area subdivisions for a 19x19 board (outlined at the top of this post).  The board area subdivisions for a 13x13 board are quite similar (outlined above).  For a 9x9 the first midline is column 5, the "second-level" midline is column 3, and the "third-level" midline is column 2, so that seems pretty straight-forward too.

**Comment by tomasmcz** [comment]
@SebKuzminsky, thank you for the excellent analysis!

This was one of the very ugly hacks I did to create a working prototype as fast as possible...

Now I think that a better way to do this would be to generate a grid, compute the perspective transformation from the given corners and apply it to the generated grid:
- the grid would be represented by endpoints for each line on the outer square
- generate an `n*n` grid in a square (with corners e.g. `(0,0), (100,0), (100, 100), (0, 100)` and other points equally distributed on the sides)
- there is a projective transformation from the generated corners to the given corners, solve the system of equations to find it
- apply the transformation to the other points.

**Comment by SebKuzminsky** [comment]
@tomasmcz, no worries, I think we've all written code that works, but that's not as pretty as it could be.  Your goal was optical board-state recognition, and this line-finding seems like one of the many problems you had to solve along the way.  You have my full respect for creating a high-quality open-source Go-board digitizer.

My math is not strong enough to know how to do the third step of your suggestion...

**Comment by tomasmcz** [comment]
Edit: This was a suggestion that turned out to be complete nonsense. For correct instructions on how to compute the projective transformation, see e.g. https://math.stackexchange.com/a/339033

**Comment by da1940430** [comment]
Amazing ! I will try @SebKuzminsky 's approach. I'm just a Taiwan student,I don't have enough ability to realize all code though I study thesis. Y'all's suggestion is helpful for me.

**Comment by da1940430** [comment]
Hi, I want to understand this part of code in `_lines()`,  please.
  ```
 else:   
        c = intersection(line(mid_line[0], corners[2]), line(corners[1], corners[3]))
        d = intersection(line(corners[0], corners[3]), line(corners[1], corners[2]))
        if d:
            l = (intersection(line(corners[0], corners[1]), line(c, d)),
                 intersection(line(corners[2], corners[3]), line(c, d)))
        else:
            lx = line(c, (c[0] + corners[0][0] - corners[3][0], 
                      c[1] + corners[0][1] - corners[3][1]))
            l = (intersection(line(corners[0], corners[1]), lx),
                 intersection(line(corners[2], corners[3]), lx))
        l2 = half_line([corners[0], l[0], l[1], corners[3]])
```

I understood when `n=0` will call itself and pass half area and `n=1`,but I can't understand this part of code mean.I just know `l2` used `l` and two boundary corners to find half line, and this line and l split this area in three regions.

**Comment by da1940430** [comment]
I succeed! But have a problem like this image's URL：https://imgur.com/R3qO867 
Angle isn't correct.

**Comment by SebKuzminsky** [comment]
That's great progress!

**Comment by tomasmcz** [comment]
So it turns out I have forgotten most of the computer vision fundamentals since writing the original program and projective transformation is a little more complicated than what I sketched above. But it's still relatively easy to figure it out, so I did that. The 19x19 grid is still hardcoded, but now you can just parametrize the calls to `gen_line(...)` in `lines(...)`.

**Comment by tomasmcz** [comment]
@da1940430 I also changed the sorting of the corners, so maybe the angle will behave differently, try it with the new version.
If you fork the repository and upload your version on GitHub, I would have a look at it.
Also, if you have any 13x13 images that you could contribute to the test repository, that would be great.

**Comment by SebKuzminsky** [comment]
I just opened tomasmcz/imago-tests#2 that adds one 9x9 test and one 13x13 test.  Both currently fail.

**Comment by da1940430** [comment]
@tomasmcz  I tried the new version, the angle was still wrong.

I'm a new user for Github, I will fork repository ,upload my version and provide image, but need some time to learn how to manipulate GitHub.
